server:
    port: 8888

logging:
    level:
        root: INFO
        org.springframework.web: INFO
        org.springframework.security: INFO
        org.springframework.security.oauth2: INFO

oauth:
    endpoints:
        registration: /oauth2/register
        authorization: /oauth2/authorize
        token: /oauth2/token
        issuer: http://localhost:8888
        jwks: /oauth2/jwks

spring:
    datasource:
        username: postgres
        password: vma3243652
        url: jdbc:postgresql://localhost:5432/Resourse_server
        jpa:
            database-platform: org.hibernate.dialect.PostgreSQL10Dialect
